version: 2

project_name: smartling-cli
dist: bin

release:
  name_template: "Version {{.Version}}"
  disable: true
  github:
    owner: Smartling
    name: smartling-cli

builds:
  -
    binary: smartling-cli

    goos:
      - linux
      - darwin
      - windows

    goarch:
      - amd64
      - arm64
      - arm

    ignore:
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm

    flags:
      - -trimpath

    ldflags:
      - -s -w
      - -X github.com/Smartling/smartling-cli/cmd/helpers/build.CommitID={{ .FullCommit }}
      - -X github.com/Smartling/smartling-cli/cmd/helpers/build.Date={{ .Date }}
      - -X github.com/Smartling/smartling-cli/cmd/helpers/build.BuiltBy=GoReleaser

archives:
  - formats: [binary]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
