// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jobsmocks

import (
	"context"

	"github.com/Smartling/smartling-cli/services/jobs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// RunFindByStrings provides a mock function for the type MockService
func (_mock *MockService) RunFindByStrings(ctx context.Context, p jobs.FindByStringsParams) (jobs.FindByStringsOutput, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for RunFindByStrings")
	}

	var r0 jobs.FindByStringsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, jobs.FindByStringsParams) (jobs.FindByStringsOutput, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, jobs.FindByStringsParams) jobs.FindByStringsOutput); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Get(0).(jobs.FindByStringsOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, jobs.FindByStringsParams) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_RunFindByStrings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunFindByStrings'
type MockService_RunFindByStrings_Call struct {
	*mock.Call
}

// RunFindByStrings is a helper method to define mock.On call
//   - ctx context.Context
//   - p jobs.FindByStringsParams
func (_e *MockService_Expecter) RunFindByStrings(ctx interface{}, p interface{}) *MockService_RunFindByStrings_Call {
	return &MockService_RunFindByStrings_Call{Call: _e.mock.On("RunFindByStrings", ctx, p)}
}

func (_c *MockService_RunFindByStrings_Call) Run(run func(ctx context.Context, p jobs.FindByStringsParams)) *MockService_RunFindByStrings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 jobs.FindByStringsParams
		if args[1] != nil {
			arg1 = args[1].(jobs.FindByStringsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RunFindByStrings_Call) Return(findByStringsOutput jobs.FindByStringsOutput, err error) *MockService_RunFindByStrings_Call {
	_c.Call.Return(findByStringsOutput, err)
	return _c
}

func (_c *MockService_RunFindByStrings_Call) RunAndReturn(run func(ctx context.Context, p jobs.FindByStringsParams) (jobs.FindByStringsOutput, error)) *MockService_RunFindByStrings_Call {
	_c.Call.Return(run)
	return _c
}

// RunList provides a mock function for the type MockService
func (_mock *MockService) RunList(ctx context.Context, p jobs.ListParams) (jobs.ListOutput, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for RunList")
	}

	var r0 jobs.ListOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, jobs.ListParams) (jobs.ListOutput, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, jobs.ListParams) jobs.ListOutput); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Get(0).(jobs.ListOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, jobs.ListParams) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_RunList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunList'
type MockService_RunList_Call struct {
	*mock.Call
}

// RunList is a helper method to define mock.On call
//   - ctx context.Context
//   - p jobs.ListParams
func (_e *MockService_Expecter) RunList(ctx interface{}, p interface{}) *MockService_RunList_Call {
	return &MockService_RunList_Call{Call: _e.mock.On("RunList", ctx, p)}
}

func (_c *MockService_RunList_Call) Run(run func(ctx context.Context, p jobs.ListParams)) *MockService_RunList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 jobs.ListParams
		if args[1] != nil {
			arg1 = args[1].(jobs.ListParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RunList_Call) Return(listOutput jobs.ListOutput, err error) *MockService_RunList_Call {
	_c.Call.Return(listOutput, err)
	return _c
}

func (_c *MockService_RunList_Call) RunAndReturn(run func(ctx context.Context, p jobs.ListParams) (jobs.ListOutput, error)) *MockService_RunList_Call {
	_c.Call.Return(run)
	return _c
}

// RunProgress provides a mock function for the type MockService
func (_mock *MockService) RunProgress(ctx context.Context, p jobs.ProgressParams) (jobs.ProgressOutput, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for RunProgress")
	}

	var r0 jobs.ProgressOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, jobs.ProgressParams) (jobs.ProgressOutput, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, jobs.ProgressParams) jobs.ProgressOutput); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Get(0).(jobs.ProgressOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, jobs.ProgressParams) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_RunProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunProgress'
type MockService_RunProgress_Call struct {
	*mock.Call
}

// RunProgress is a helper method to define mock.On call
//   - ctx context.Context
//   - p jobs.ProgressParams
func (_e *MockService_Expecter) RunProgress(ctx interface{}, p interface{}) *MockService_RunProgress_Call {
	return &MockService_RunProgress_Call{Call: _e.mock.On("RunProgress", ctx, p)}
}

func (_c *MockService_RunProgress_Call) Run(run func(ctx context.Context, p jobs.ProgressParams)) *MockService_RunProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 jobs.ProgressParams
		if args[1] != nil {
			arg1 = args[1].(jobs.ProgressParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RunProgress_Call) Return(progressOutput jobs.ProgressOutput, err error) *MockService_RunProgress_Call {
	_c.Call.Return(progressOutput, err)
	return _c
}

func (_c *MockService_RunProgress_Call) RunAndReturn(run func(ctx context.Context, p jobs.ProgressParams) (jobs.ProgressOutput, error)) *MockService_RunProgress_Call {
	_c.Call.Return(run)
	return _c
}

// RunView provides a mock function for the type MockService
func (_mock *MockService) RunView(ctx context.Context, p jobs.ViewParams) (jobs.ViewOutput, error) {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for RunView")
	}

	var r0 jobs.ViewOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, jobs.ViewParams) (jobs.ViewOutput, error)); ok {
		return returnFunc(ctx, p)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, jobs.ViewParams) jobs.ViewOutput); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Get(0).(jobs.ViewOutput)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, jobs.ViewParams) error); ok {
		r1 = returnFunc(ctx, p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_RunView_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunView'
type MockService_RunView_Call struct {
	*mock.Call
}

// RunView is a helper method to define mock.On call
//   - ctx context.Context
//   - p jobs.ViewParams
func (_e *MockService_Expecter) RunView(ctx interface{}, p interface{}) *MockService_RunView_Call {
	return &MockService_RunView_Call{Call: _e.mock.On("RunView", ctx, p)}
}

func (_c *MockService_RunView_Call) Run(run func(ctx context.Context, p jobs.ViewParams)) *MockService_RunView_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 jobs.ViewParams
		if args[1] != nil {
			arg1 = args[1].(jobs.ViewParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RunView_Call) Return(viewOutput jobs.ViewOutput, err error) *MockService_RunView_Call {
	_c.Call.Return(viewOutput, err)
	return _c
}

func (_c *MockService_RunView_Call) RunAndReturn(run func(ctx context.Context, p jobs.ViewParams) (jobs.ViewOutput, error)) *MockService_RunView_Call {
	_c.Call.Return(run)
	return _c
}
