// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package projectsmocks

import (
	"context"

	"github.com/Smartling/smartling-cli/services/projects"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// RunInfo provides a mock function for the type MockService
func (_mock *MockService) RunInfo(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunInfo")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RunInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunInfo'
type MockService_RunInfo_Call struct {
	*mock.Call
}

// RunInfo is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) RunInfo(ctx interface{}) *MockService_RunInfo_Call {
	return &MockService_RunInfo_Call{Call: _e.mock.On("RunInfo", ctx)}
}

func (_c *MockService_RunInfo_Call) Run(run func(ctx context.Context)) *MockService_RunInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_RunInfo_Call) Return(err error) *MockService_RunInfo_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RunInfo_Call) RunAndReturn(run func(ctx context.Context) error) *MockService_RunInfo_Call {
	_c.Call.Return(run)
	return _c
}

// RunList provides a mock function for the type MockService
func (_mock *MockService) RunList(ctx context.Context, short bool) error {
	ret := _mock.Called(ctx, short)

	if len(ret) == 0 {
		panic("no return value specified for RunList")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool) error); ok {
		r0 = returnFunc(ctx, short)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RunList_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunList'
type MockService_RunList_Call struct {
	*mock.Call
}

// RunList is a helper method to define mock.On call
//   - ctx context.Context
//   - short bool
func (_e *MockService_Expecter) RunList(ctx interface{}, short interface{}) *MockService_RunList_Call {
	return &MockService_RunList_Call{Call: _e.mock.On("RunList", ctx, short)}
}

func (_c *MockService_RunList_Call) Run(run func(ctx context.Context, short bool)) *MockService_RunList_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RunList_Call) Return(err error) *MockService_RunList_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RunList_Call) RunAndReturn(run func(ctx context.Context, short bool) error) *MockService_RunList_Call {
	_c.Call.Return(run)
	return _c
}

// RunLocales provides a mock function for the type MockService
func (_mock *MockService) RunLocales(ctx context.Context, params projects.LocalesParams) error {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for RunLocales")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, projects.LocalesParams) error); ok {
		r0 = returnFunc(ctx, params)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_RunLocales_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunLocales'
type MockService_RunLocales_Call struct {
	*mock.Call
}

// RunLocales is a helper method to define mock.On call
//   - ctx context.Context
//   - params projects.LocalesParams
func (_e *MockService_Expecter) RunLocales(ctx interface{}, params interface{}) *MockService_RunLocales_Call {
	return &MockService_RunLocales_Call{Call: _e.mock.On("RunLocales", ctx, params)}
}

func (_c *MockService_RunLocales_Call) Run(run func(ctx context.Context, params projects.LocalesParams)) *MockService_RunLocales_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 projects.LocalesParams
		if args[1] != nil {
			arg1 = args[1].(projects.LocalesParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_RunLocales_Call) Return(err error) *MockService_RunLocales_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_RunLocales_Call) RunAndReturn(run func(ctx context.Context, params projects.LocalesParams) error) *MockService_RunLocales_Call {
	_c.Call.Return(run)
	return _c
}
