// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mtmocks

import (
	"context"

	"github.com/Smartling/smartling-cli/services/mt"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSrvInitializer creates a new instance of MockSrvInitializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSrvInitializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSrvInitializer {
	mock := &MockSrvInitializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSrvInitializer is an autogenerated mock type for the SrvInitializer type
type MockSrvInitializer struct {
	mock.Mock
}

type MockSrvInitializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSrvInitializer) EXPECT() *MockSrvInitializer_Expecter {
	return &MockSrvInitializer_Expecter{mock: &_m.Mock}
}

// InitMTSrv provides a mock function for the type MockSrvInitializer
func (_mock *MockSrvInitializer) InitMTSrv(ctx context.Context) (mt.Service, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for InitMTSrv")
	}

	var r0 mt.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (mt.Service, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) mt.Service); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mt.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSrvInitializer_InitMTSrv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitMTSrv'
type MockSrvInitializer_InitMTSrv_Call struct {
	*mock.Call
}

// InitMTSrv is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSrvInitializer_Expecter) InitMTSrv(ctx interface{}) *MockSrvInitializer_InitMTSrv_Call {
	return &MockSrvInitializer_InitMTSrv_Call{Call: _e.mock.On("InitMTSrv", ctx)}
}

func (_c *MockSrvInitializer_InitMTSrv_Call) Run(run func(ctx context.Context)) *MockSrvInitializer_InitMTSrv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSrvInitializer_InitMTSrv_Call) Return(service mt.Service, err error) *MockSrvInitializer_InitMTSrv_Call {
	_c.Call.Return(service, err)
	return _c
}

func (_c *MockSrvInitializer_InitMTSrv_Call) RunAndReturn(run func(ctx context.Context) (mt.Service, error)) *MockSrvInitializer_InitMTSrv_Call {
	_c.Call.Return(run)
	return _c
}
