// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mtmocks

import (
	"github.com/Smartling/smartling-cli/services/helpers/glob_files"
	"github.com/Smartling/smartling-cli/services/mt"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSrvInitializer creates a new instance of MockSrvInitializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSrvInitializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSrvInitializer {
	mock := &MockSrvInitializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSrvInitializer is an autogenerated mock type for the SrvInitializer type
type MockSrvInitializer struct {
	mock.Mock
}

type MockSrvInitializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSrvInitializer) EXPECT() *MockSrvInitializer_Expecter {
	return &MockSrvInitializer_Expecter{mock: &_m.Mock}
}

// InitMTSrv provides a mock function for the type MockSrvInitializer
func (_mock *MockSrvInitializer) InitMTSrv() (mt.Service, globfiles.ListFilesFn, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitMTSrv")
	}

	var r0 mt.Service
	var r1 globfiles.ListFilesFn
	var r2 error
	if returnFunc, ok := ret.Get(0).(func() (mt.Service, globfiles.ListFilesFn, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() mt.Service); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(mt.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() globfiles.ListFilesFn); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(globfiles.ListFilesFn)
		}
	}
	if returnFunc, ok := ret.Get(2).(func() error); ok {
		r2 = returnFunc()
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSrvInitializer_InitMTSrv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitMTSrv'
type MockSrvInitializer_InitMTSrv_Call struct {
	*mock.Call
}

// InitMTSrv is a helper method to define mock.On call
func (_e *MockSrvInitializer_Expecter) InitMTSrv() *MockSrvInitializer_InitMTSrv_Call {
	return &MockSrvInitializer_InitMTSrv_Call{Call: _e.mock.On("InitMTSrv")}
}

func (_c *MockSrvInitializer_InitMTSrv_Call) Run(run func()) *MockSrvInitializer_InitMTSrv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSrvInitializer_InitMTSrv_Call) Return(service mt.Service, listFilesFn globfiles.ListFilesFn, err error) *MockSrvInitializer_InitMTSrv_Call {
	_c.Call.Return(service, listFilesFn, err)
	return _c
}

func (_c *MockSrvInitializer_InitMTSrv_Call) RunAndReturn(run func() (mt.Service, globfiles.ListFilesFn, error)) *MockSrvInitializer_InitMTSrv_Call {
	_c.Call.Return(run)
	return _c
}
