// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jobstringmocks

import (
	"context"

	"github.com/Smartling/api-sdk-go/api/job/string"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJobString creates a new instance of MockJobString. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobString(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobString {
	mock := &MockJobString{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobString is an autogenerated mock type for the JobString type
type MockJobString struct {
	mock.Mock
}

type MockJobString_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobString) EXPECT() *MockJobString_Expecter {
	return &MockJobString_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockJobString
func (_mock *MockJobString) Add(ctx context.Context, projectID string, translationJobUID string, req jobstring.AddRequest) (jobstring.Result, error) {
	ret := _mock.Called(ctx, projectID, translationJobUID, req)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 jobstring.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, jobstring.AddRequest) (jobstring.Result, error)); ok {
		return returnFunc(ctx, projectID, translationJobUID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, jobstring.AddRequest) jobstring.Result); ok {
		r0 = returnFunc(ctx, projectID, translationJobUID, req)
	} else {
		r0 = ret.Get(0).(jobstring.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, jobstring.AddRequest) error); ok {
		r1 = returnFunc(ctx, projectID, translationJobUID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobString_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockJobString_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - translationJobUID string
//   - req jobstring.AddRequest
func (_e *MockJobString_Expecter) Add(ctx interface{}, projectID interface{}, translationJobUID interface{}, req interface{}) *MockJobString_Add_Call {
	return &MockJobString_Add_Call{Call: _e.mock.On("Add", ctx, projectID, translationJobUID, req)}
}

func (_c *MockJobString_Add_Call) Run(run func(ctx context.Context, projectID string, translationJobUID string, req jobstring.AddRequest)) *MockJobString_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 jobstring.AddRequest
		if args[3] != nil {
			arg3 = args[3].(jobstring.AddRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockJobString_Add_Call) Return(result jobstring.Result, err error) *MockJobString_Add_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockJobString_Add_Call) RunAndReturn(run func(ctx context.Context, projectID string, translationJobUID string, req jobstring.AddRequest) (jobstring.Result, error)) *MockJobString_Add_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockJobString
func (_mock *MockJobString) List(ctx context.Context, projectID string, translationJobUID string, params jobstring.ListParams) (jobstring.ListResponse, error) {
	ret := _mock.Called(ctx, projectID, translationJobUID, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 jobstring.ListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, jobstring.ListParams) (jobstring.ListResponse, error)); ok {
		return returnFunc(ctx, projectID, translationJobUID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, jobstring.ListParams) jobstring.ListResponse); ok {
		r0 = returnFunc(ctx, projectID, translationJobUID, params)
	} else {
		r0 = ret.Get(0).(jobstring.ListResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, jobstring.ListParams) error); ok {
		r1 = returnFunc(ctx, projectID, translationJobUID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobString_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockJobString_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - translationJobUID string
//   - params jobstring.ListParams
func (_e *MockJobString_Expecter) List(ctx interface{}, projectID interface{}, translationJobUID interface{}, params interface{}) *MockJobString_List_Call {
	return &MockJobString_List_Call{Call: _e.mock.On("List", ctx, projectID, translationJobUID, params)}
}

func (_c *MockJobString_List_Call) Run(run func(ctx context.Context, projectID string, translationJobUID string, params jobstring.ListParams)) *MockJobString_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 jobstring.ListParams
		if args[3] != nil {
			arg3 = args[3].(jobstring.ListParams)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockJobString_List_Call) Return(listResponse jobstring.ListResponse, err error) *MockJobString_List_Call {
	_c.Call.Return(listResponse, err)
	return _c
}

func (_c *MockJobString_List_Call) RunAndReturn(run func(ctx context.Context, projectID string, translationJobUID string, params jobstring.ListParams) (jobstring.ListResponse, error)) *MockJobString_List_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockJobString
func (_mock *MockJobString) Remove(ctx context.Context, projectID string, translationJobUID string, req jobstring.RemoveRequest) (jobstring.Result, error) {
	ret := _mock.Called(ctx, projectID, translationJobUID, req)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 jobstring.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, jobstring.RemoveRequest) (jobstring.Result, error)); ok {
		return returnFunc(ctx, projectID, translationJobUID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, jobstring.RemoveRequest) jobstring.Result); ok {
		r0 = returnFunc(ctx, projectID, translationJobUID, req)
	} else {
		r0 = ret.Get(0).(jobstring.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, jobstring.RemoveRequest) error); ok {
		r1 = returnFunc(ctx, projectID, translationJobUID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJobString_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockJobString_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - translationJobUID string
//   - req jobstring.RemoveRequest
func (_e *MockJobString_Expecter) Remove(ctx interface{}, projectID interface{}, translationJobUID interface{}, req interface{}) *MockJobString_Remove_Call {
	return &MockJobString_Remove_Call{Call: _e.mock.On("Remove", ctx, projectID, translationJobUID, req)}
}

func (_c *MockJobString_Remove_Call) Run(run func(ctx context.Context, projectID string, translationJobUID string, req jobstring.RemoveRequest)) *MockJobString_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 jobstring.RemoveRequest
		if args[3] != nil {
			arg3 = args[3].(jobstring.RemoveRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockJobString_Remove_Call) Return(result jobstring.Result, err error) *MockJobString_Remove_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockJobString_Remove_Call) RunAndReturn(run func(ctx context.Context, projectID string, translationJobUID string, req jobstring.RemoveRequest) (jobstring.Result, error)) *MockJobString_Remove_Call {
	_c.Call.Return(run)
	return _c
}
