// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package localemocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockJobLocale creates a new instance of MockJobLocale. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJobLocale(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJobLocale {
	mock := &MockJobLocale{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJobLocale is an autogenerated mock type for the JobLocale type
type MockJobLocale struct {
	mock.Mock
}

type MockJobLocale_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJobLocale) EXPECT() *MockJobLocale_Expecter {
	return &MockJobLocale_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockJobLocale
func (_mock *MockJobLocale) Add(ctx context.Context, projectID string, translationJobUID string, targetLocaleID string) error {
	ret := _mock.Called(ctx, projectID, translationJobUID, targetLocaleID)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, projectID, translationJobUID, targetLocaleID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobLocale_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockJobLocale_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - translationJobUID string
//   - targetLocaleID string
func (_e *MockJobLocale_Expecter) Add(ctx interface{}, projectID interface{}, translationJobUID interface{}, targetLocaleID interface{}) *MockJobLocale_Add_Call {
	return &MockJobLocale_Add_Call{Call: _e.mock.On("Add", ctx, projectID, translationJobUID, targetLocaleID)}
}

func (_c *MockJobLocale_Add_Call) Run(run func(ctx context.Context, projectID string, translationJobUID string, targetLocaleID string)) *MockJobLocale_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockJobLocale_Add_Call) Return(err error) *MockJobLocale_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobLocale_Add_Call) RunAndReturn(run func(ctx context.Context, projectID string, translationJobUID string, targetLocaleID string) error) *MockJobLocale_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockJobLocale
func (_mock *MockJobLocale) Remove(ctx context.Context, projectID string, translationJobUID string, targetLocaleID string) error {
	ret := _mock.Called(ctx, projectID, translationJobUID, targetLocaleID)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, projectID, translationJobUID, targetLocaleID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockJobLocale_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockJobLocale_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - translationJobUID string
//   - targetLocaleID string
func (_e *MockJobLocale_Expecter) Remove(ctx interface{}, projectID interface{}, translationJobUID interface{}, targetLocaleID interface{}) *MockJobLocale_Remove_Call {
	return &MockJobLocale_Remove_Call{Call: _e.mock.On("Remove", ctx, projectID, translationJobUID, targetLocaleID)}
}

func (_c *MockJobLocale_Remove_Call) Run(run func(ctx context.Context, projectID string, translationJobUID string, targetLocaleID string)) *MockJobLocale_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockJobLocale_Remove_Call) Return(err error) *MockJobLocale_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockJobLocale_Remove_Call) RunAndReturn(run func(ctx context.Context, projectID string, translationJobUID string, targetLocaleID string) error) *MockJobLocale_Remove_Call {
	_c.Call.Return(run)
	return _c
}
