// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package projectsmocks

import (
	"github.com/Smartling/smartling-cli/services/projects"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSrvInitializer creates a new instance of MockSrvInitializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSrvInitializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSrvInitializer {
	mock := &MockSrvInitializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSrvInitializer is an autogenerated mock type for the SrvInitializer type
type MockSrvInitializer struct {
	mock.Mock
}

type MockSrvInitializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSrvInitializer) EXPECT() *MockSrvInitializer_Expecter {
	return &MockSrvInitializer_Expecter{mock: &_m.Mock}
}

// InitProjectsSrv provides a mock function for the type MockSrvInitializer
func (_mock *MockSrvInitializer) InitProjectsSrv() (projects.Service, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for InitProjectsSrv")
	}

	var r0 projects.Service
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (projects.Service, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() projects.Service); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(projects.Service)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSrvInitializer_InitProjectsSrv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InitProjectsSrv'
type MockSrvInitializer_InitProjectsSrv_Call struct {
	*mock.Call
}

// InitProjectsSrv is a helper method to define mock.On call
func (_e *MockSrvInitializer_Expecter) InitProjectsSrv() *MockSrvInitializer_InitProjectsSrv_Call {
	return &MockSrvInitializer_InitProjectsSrv_Call{Call: _e.mock.On("InitProjectsSrv")}
}

func (_c *MockSrvInitializer_InitProjectsSrv_Call) Run(run func()) *MockSrvInitializer_InitProjectsSrv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSrvInitializer_InitProjectsSrv_Call) Return(service projects.Service, err error) *MockSrvInitializer_InitProjectsSrv_Call {
	_c.Call.Return(service, err)
	return _c
}

func (_c *MockSrvInitializer_InitProjectsSrv_Call) RunAndReturn(run func() (projects.Service, error)) *MockSrvInitializer_InitProjectsSrv_Call {
	_c.Call.Return(run)
	return _c
}
