// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jobmocks

import (
	"context"

	"github.com/Smartling/api-sdk-go/api/job"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJob creates a new instance of MockJob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJob(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJob {
	mock := &MockJob{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJob is an autogenerated mock type for the Job type
type MockJob struct {
	mock.Mock
}

type MockJob_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJob) EXPECT() *MockJob_Expecter {
	return &MockJob_Expecter{mock: &_m.Mock}
}

// GetJob provides a mock function for the type MockJob
func (_mock *MockJob) GetJob(ctx context.Context, projectID string, jobUID string) (job.GetJobResponse, error) {
	ret := _mock.Called(ctx, projectID, jobUID)

	if len(ret) == 0 {
		panic("no return value specified for GetJob")
	}

	var r0 job.GetJobResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (job.GetJobResponse, error)); ok {
		return returnFunc(ctx, projectID, jobUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) job.GetJobResponse); ok {
		r0 = returnFunc(ctx, projectID, jobUID)
	} else {
		r0 = ret.Get(0).(job.GetJobResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, projectID, jobUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJob_GetJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJob'
type MockJob_GetJob_Call struct {
	*mock.Call
}

// GetJob is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - jobUID string
func (_e *MockJob_Expecter) GetJob(ctx interface{}, projectID interface{}, jobUID interface{}) *MockJob_GetJob_Call {
	return &MockJob_GetJob_Call{Call: _e.mock.On("GetJob", ctx, projectID, jobUID)}
}

func (_c *MockJob_GetJob_Call) Run(run func(ctx context.Context, projectID string, jobUID string)) *MockJob_GetJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJob_GetJob_Call) Return(getJobResponse job.GetJobResponse, err error) *MockJob_GetJob_Call {
	_c.Call.Return(getJobResponse, err)
	return _c
}

func (_c *MockJob_GetJob_Call) RunAndReturn(run func(ctx context.Context, projectID string, jobUID string) (job.GetJobResponse, error)) *MockJob_GetJob_Call {
	_c.Call.Return(run)
	return _c
}

// ListFiles provides a mock function for the type MockJob
func (_mock *MockJob) ListFiles(ctx context.Context, projectID string, jobUID string, limit uint32, offset uint32) (job.ListJobFilesResponse, error) {
	ret := _mock.Called(ctx, projectID, jobUID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListFiles")
	}

	var r0 job.ListJobFilesResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, uint32, uint32) (job.ListJobFilesResponse, error)); ok {
		return returnFunc(ctx, projectID, jobUID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, uint32, uint32) job.ListJobFilesResponse); ok {
		r0 = returnFunc(ctx, projectID, jobUID, limit, offset)
	} else {
		r0 = ret.Get(0).(job.ListJobFilesResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, uint32, uint32) error); ok {
		r1 = returnFunc(ctx, projectID, jobUID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJob_ListFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFiles'
type MockJob_ListFiles_Call struct {
	*mock.Call
}

// ListFiles is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - jobUID string
//   - limit uint32
//   - offset uint32
func (_e *MockJob_Expecter) ListFiles(ctx interface{}, projectID interface{}, jobUID interface{}, limit interface{}, offset interface{}) *MockJob_ListFiles_Call {
	return &MockJob_ListFiles_Call{Call: _e.mock.On("ListFiles", ctx, projectID, jobUID, limit, offset)}
}

func (_c *MockJob_ListFiles_Call) Run(run func(ctx context.Context, projectID string, jobUID string, limit uint32, offset uint32)) *MockJob_ListFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uint32
		if args[3] != nil {
			arg3 = args[3].(uint32)
		}
		var arg4 uint32
		if args[4] != nil {
			arg4 = args[4].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockJob_ListFiles_Call) Return(listJobFilesResponse job.ListJobFilesResponse, err error) *MockJob_ListFiles_Call {
	_c.Call.Return(listJobFilesResponse, err)
	return _c
}

func (_c *MockJob_ListFiles_Call) RunAndReturn(run func(ctx context.Context, projectID string, jobUID string, limit uint32, offset uint32) (job.ListJobFilesResponse, error)) *MockJob_ListFiles_Call {
	_c.Call.Return(run)
	return _c
}

// Progress provides a mock function for the type MockJob
func (_mock *MockJob) Progress(ctx context.Context, projectID string, jobUID string) (job.GetJobProgressResponse, error) {
	ret := _mock.Called(ctx, projectID, jobUID)

	if len(ret) == 0 {
		panic("no return value specified for Progress")
	}

	var r0 job.GetJobProgressResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (job.GetJobProgressResponse, error)); ok {
		return returnFunc(ctx, projectID, jobUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) job.GetJobProgressResponse); ok {
		r0 = returnFunc(ctx, projectID, jobUID)
	} else {
		r0 = ret.Get(0).(job.GetJobProgressResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, projectID, jobUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJob_Progress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Progress'
type MockJob_Progress_Call struct {
	*mock.Call
}

// Progress is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - jobUID string
func (_e *MockJob_Expecter) Progress(ctx interface{}, projectID interface{}, jobUID interface{}) *MockJob_Progress_Call {
	return &MockJob_Progress_Call{Call: _e.mock.On("Progress", ctx, projectID, jobUID)}
}

func (_c *MockJob_Progress_Call) Run(run func(ctx context.Context, projectID string, jobUID string)) *MockJob_Progress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJob_Progress_Call) Return(getJobProgressResponse job.GetJobProgressResponse, err error) *MockJob_Progress_Call {
	_c.Call.Return(getJobProgressResponse, err)
	return _c
}

func (_c *MockJob_Progress_Call) RunAndReturn(run func(ctx context.Context, projectID string, jobUID string) (job.GetJobProgressResponse, error)) *MockJob_Progress_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByName provides a mock function for the type MockJob
func (_mock *MockJob) SearchByName(ctx context.Context, projectID string, name string) ([]job.GetJobResponse, error) {
	ret := _mock.Called(ctx, projectID, name)

	if len(ret) == 0 {
		panic("no return value specified for SearchByName")
	}

	var r0 []job.GetJobResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]job.GetJobResponse, error)); ok {
		return returnFunc(ctx, projectID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []job.GetJobResponse); ok {
		r0 = returnFunc(ctx, projectID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]job.GetJobResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, projectID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJob_SearchByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByName'
type MockJob_SearchByName_Call struct {
	*mock.Call
}

// SearchByName is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - name string
func (_e *MockJob_Expecter) SearchByName(ctx interface{}, projectID interface{}, name interface{}) *MockJob_SearchByName_Call {
	return &MockJob_SearchByName_Call{Call: _e.mock.On("SearchByName", ctx, projectID, name)}
}

func (_c *MockJob_SearchByName_Call) Run(run func(ctx context.Context, projectID string, name string)) *MockJob_SearchByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJob_SearchByName_Call) Return(jobs []job.GetJobResponse, err error) *MockJob_SearchByName_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *MockJob_SearchByName_Call) RunAndReturn(run func(ctx context.Context, projectID string, name string) ([]job.GetJobResponse, error)) *MockJob_SearchByName_Call {
	_c.Call.Return(run)
	return _c
}
