// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jobmocks

import (
	"context"

	"github.com/Smartling/api-sdk-go/api/job"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJob creates a new instance of MockJob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJob(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJob {
	mock := &MockJob{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJob is an autogenerated mock type for the Job type
type MockJob struct {
	mock.Mock
}

type MockJob_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJob) EXPECT() *MockJob_Expecter {
	return &MockJob_Expecter{mock: &_m.Mock}
}

// GetJob provides a mock function for the type MockJob
func (_mock *MockJob) GetJob(ctx context.Context, projectID string, translationJobUID string) (job.GetJobResponse, error) {
	ret := _mock.Called(ctx, projectID, translationJobUID)

	if len(ret) == 0 {
		panic("no return value specified for GetJob")
	}

	var r0 job.GetJobResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (job.GetJobResponse, error)); ok {
		return returnFunc(ctx, projectID, translationJobUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) job.GetJobResponse); ok {
		r0 = returnFunc(ctx, projectID, translationJobUID)
	} else {
		r0 = ret.Get(0).(job.GetJobResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, projectID, translationJobUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJob_GetJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJob'
type MockJob_GetJob_Call struct {
	*mock.Call
}

// GetJob is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - translationJobUID string
func (_e *MockJob_Expecter) GetJob(ctx interface{}, projectID interface{}, translationJobUID interface{}) *MockJob_GetJob_Call {
	return &MockJob_GetJob_Call{Call: _e.mock.On("GetJob", ctx, projectID, translationJobUID)}
}

func (_c *MockJob_GetJob_Call) Run(run func(ctx context.Context, projectID string, translationJobUID string)) *MockJob_GetJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJob_GetJob_Call) Return(getJobResponse job.GetJobResponse, err error) *MockJob_GetJob_Call {
	_c.Call.Return(getJobResponse, err)
	return _c
}

func (_c *MockJob_GetJob_Call) RunAndReturn(run func(ctx context.Context, projectID string, translationJobUID string) (job.GetJobResponse, error)) *MockJob_GetJob_Call {
	_c.Call.Return(run)
	return _c
}

// Progress provides a mock function for the type MockJob
func (_mock *MockJob) Progress(ctx context.Context, projectID string, translationJobUID string) (job.GetJobProgressResponse, error) {
	ret := _mock.Called(ctx, projectID, translationJobUID)

	if len(ret) == 0 {
		panic("no return value specified for Progress")
	}

	var r0 job.GetJobProgressResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (job.GetJobProgressResponse, error)); ok {
		return returnFunc(ctx, projectID, translationJobUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) job.GetJobProgressResponse); ok {
		r0 = returnFunc(ctx, projectID, translationJobUID)
	} else {
		r0 = ret.Get(0).(job.GetJobProgressResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, projectID, translationJobUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJob_Progress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Progress'
type MockJob_Progress_Call struct {
	*mock.Call
}

// Progress is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - translationJobUID string
func (_e *MockJob_Expecter) Progress(ctx interface{}, projectID interface{}, translationJobUID interface{}) *MockJob_Progress_Call {
	return &MockJob_Progress_Call{Call: _e.mock.On("Progress", ctx, projectID, translationJobUID)}
}

func (_c *MockJob_Progress_Call) Run(run func(ctx context.Context, projectID string, translationJobUID string)) *MockJob_Progress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJob_Progress_Call) Return(getJobProgressResponse job.GetJobProgressResponse, err error) *MockJob_Progress_Call {
	_c.Call.Return(getJobProgressResponse, err)
	return _c
}

func (_c *MockJob_Progress_Call) RunAndReturn(run func(ctx context.Context, projectID string, translationJobUID string) (job.GetJobProgressResponse, error)) *MockJob_Progress_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByName provides a mock function for the type MockJob
func (_mock *MockJob) SearchByName(ctx context.Context, projectID string, name string) ([]job.GetJobResponse, error) {
	ret := _mock.Called(ctx, projectID, name)

	if len(ret) == 0 {
		panic("no return value specified for SearchByName")
	}

	var r0 []job.GetJobResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]job.GetJobResponse, error)); ok {
		return returnFunc(ctx, projectID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []job.GetJobResponse); ok {
		r0 = returnFunc(ctx, projectID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]job.GetJobResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, projectID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJob_SearchByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByName'
type MockJob_SearchByName_Call struct {
	*mock.Call
}

// SearchByName is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - name string
func (_e *MockJob_Expecter) SearchByName(ctx interface{}, projectID interface{}, name interface{}) *MockJob_SearchByName_Call {
	return &MockJob_SearchByName_Call{Call: _e.mock.On("SearchByName", ctx, projectID, name)}
}

func (_c *MockJob_SearchByName_Call) Run(run func(ctx context.Context, projectID string, name string)) *MockJob_SearchByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJob_SearchByName_Call) Return(jobs []job.GetJobResponse, err error) *MockJob_SearchByName_Call {
	_c.Call.Return(jobs, err)
	return _c
}

func (_c *MockJob_SearchByName_Call) RunAndReturn(run func(ctx context.Context, projectID string, name string) ([]job.GetJobResponse, error)) *MockJob_SearchByName_Call {
	_c.Call.Return(run)
	return _c
}
