// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package jobmocks

import (
	"context"

	"github.com/Smartling/api-sdk-go/api/job"
	mock "github.com/stretchr/testify/mock"
)

// NewMockJob creates a new instance of MockJob. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockJob(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockJob {
	mock := &MockJob{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockJob is an autogenerated mock type for the Job type
type MockJob struct {
	mock.Mock
}

type MockJob_Expecter struct {
	mock *mock.Mock
}

func (_m *MockJob) EXPECT() *MockJob_Expecter {
	return &MockJob_Expecter{mock: &_m.Mock}
}

// GetJob provides a mock function for the type MockJob
func (_mock *MockJob) GetJob(ctx context.Context, projectID string, jobUID string) (job.GetJobResponse, error) {
	ret := _mock.Called(ctx, projectID, jobUID)

	if len(ret) == 0 {
		panic("no return value specified for GetJob")
	}

	var r0 job.GetJobResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (job.GetJobResponse, error)); ok {
		return returnFunc(ctx, projectID, jobUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) job.GetJobResponse); ok {
		r0 = returnFunc(ctx, projectID, jobUID)
	} else {
		r0 = ret.Get(0).(job.GetJobResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, projectID, jobUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJob_GetJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJob'
type MockJob_GetJob_Call struct {
	*mock.Call
}

// GetJob is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - jobUID string
func (_e *MockJob_Expecter) GetJob(ctx interface{}, projectID interface{}, jobUID interface{}) *MockJob_GetJob_Call {
	return &MockJob_GetJob_Call{Call: _e.mock.On("GetJob", ctx, projectID, jobUID)}
}

func (_c *MockJob_GetJob_Call) Run(run func(ctx context.Context, projectID string, jobUID string)) *MockJob_GetJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJob_GetJob_Call) Return(getJobResponse job.GetJobResponse, err error) *MockJob_GetJob_Call {
	_c.Call.Return(getJobResponse, err)
	return _c
}

func (_c *MockJob_GetJob_Call) RunAndReturn(run func(ctx context.Context, projectID string, jobUID string) (job.GetJobResponse, error)) *MockJob_GetJob_Call {
	_c.Call.Return(run)
	return _c
}

// ListAccountJobs provides a mock function for the type MockJob
func (_mock *MockJob) ListAccountJobs(ctx context.Context, accountUID string, params job.ListAccountJobsParams) (job.ListJobsResponse, error) {
	ret := _mock.Called(ctx, accountUID, params)

	if len(ret) == 0 {
		panic("no return value specified for ListAccountJobs")
	}

	var r0 job.ListJobsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, job.ListAccountJobsParams) (job.ListJobsResponse, error)); ok {
		return returnFunc(ctx, accountUID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, job.ListAccountJobsParams) job.ListJobsResponse); ok {
		r0 = returnFunc(ctx, accountUID, params)
	} else {
		r0 = ret.Get(0).(job.ListJobsResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, job.ListAccountJobsParams) error); ok {
		r1 = returnFunc(ctx, accountUID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJob_ListAccountJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAccountJobs'
type MockJob_ListAccountJobs_Call struct {
	*mock.Call
}

// ListAccountJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - accountUID string
//   - params job.ListAccountJobsParams
func (_e *MockJob_Expecter) ListAccountJobs(ctx interface{}, accountUID interface{}, params interface{}) *MockJob_ListAccountJobs_Call {
	return &MockJob_ListAccountJobs_Call{Call: _e.mock.On("ListAccountJobs", ctx, accountUID, params)}
}

func (_c *MockJob_ListAccountJobs_Call) Run(run func(ctx context.Context, accountUID string, params job.ListAccountJobsParams)) *MockJob_ListAccountJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 job.ListAccountJobsParams
		if args[2] != nil {
			arg2 = args[2].(job.ListAccountJobsParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJob_ListAccountJobs_Call) Return(listJobsResponse job.ListJobsResponse, err error) *MockJob_ListAccountJobs_Call {
	_c.Call.Return(listJobsResponse, err)
	return _c
}

func (_c *MockJob_ListAccountJobs_Call) RunAndReturn(run func(ctx context.Context, accountUID string, params job.ListAccountJobsParams) (job.ListJobsResponse, error)) *MockJob_ListAccountJobs_Call {
	_c.Call.Return(run)
	return _c
}

// ListProjectJobs provides a mock function for the type MockJob
func (_mock *MockJob) ListProjectJobs(ctx context.Context, projectID string, params job.ListProjectJobsParams) (job.ListJobsResponse, error) {
	ret := _mock.Called(ctx, projectID, params)

	if len(ret) == 0 {
		panic("no return value specified for ListProjectJobs")
	}

	var r0 job.ListJobsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, job.ListProjectJobsParams) (job.ListJobsResponse, error)); ok {
		return returnFunc(ctx, projectID, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, job.ListProjectJobsParams) job.ListJobsResponse); ok {
		r0 = returnFunc(ctx, projectID, params)
	} else {
		r0 = ret.Get(0).(job.ListJobsResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, job.ListProjectJobsParams) error); ok {
		r1 = returnFunc(ctx, projectID, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJob_ListProjectJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProjectJobs'
type MockJob_ListProjectJobs_Call struct {
	*mock.Call
}

// ListProjectJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - params job.ListProjectJobsParams
func (_e *MockJob_Expecter) ListProjectJobs(ctx interface{}, projectID interface{}, params interface{}) *MockJob_ListProjectJobs_Call {
	return &MockJob_ListProjectJobs_Call{Call: _e.mock.On("ListProjectJobs", ctx, projectID, params)}
}

func (_c *MockJob_ListProjectJobs_Call) Run(run func(ctx context.Context, projectID string, params job.ListProjectJobsParams)) *MockJob_ListProjectJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 job.ListProjectJobsParams
		if args[2] != nil {
			arg2 = args[2].(job.ListProjectJobsParams)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJob_ListProjectJobs_Call) Return(listJobsResponse job.ListJobsResponse, err error) *MockJob_ListProjectJobs_Call {
	_c.Call.Return(listJobsResponse, err)
	return _c
}

func (_c *MockJob_ListProjectJobs_Call) RunAndReturn(run func(ctx context.Context, projectID string, params job.ListProjectJobsParams) (job.ListJobsResponse, error)) *MockJob_ListProjectJobs_Call {
	_c.Call.Return(run)
	return _c
}

// Progress provides a mock function for the type MockJob
func (_mock *MockJob) Progress(ctx context.Context, projectID string, jobUID string) (job.GetJobProgressResponse, error) {
	ret := _mock.Called(ctx, projectID, jobUID)

	if len(ret) == 0 {
		panic("no return value specified for Progress")
	}

	var r0 job.GetJobProgressResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (job.GetJobProgressResponse, error)); ok {
		return returnFunc(ctx, projectID, jobUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) job.GetJobProgressResponse); ok {
		r0 = returnFunc(ctx, projectID, jobUID)
	} else {
		r0 = ret.Get(0).(job.GetJobProgressResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, projectID, jobUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJob_Progress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Progress'
type MockJob_Progress_Call struct {
	*mock.Call
}

// Progress is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - jobUID string
func (_e *MockJob_Expecter) Progress(ctx interface{}, projectID interface{}, jobUID interface{}) *MockJob_Progress_Call {
	return &MockJob_Progress_Call{Call: _e.mock.On("Progress", ctx, projectID, jobUID)}
}

func (_c *MockJob_Progress_Call) Run(run func(ctx context.Context, projectID string, jobUID string)) *MockJob_Progress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJob_Progress_Call) Return(getJobProgressResponse job.GetJobProgressResponse, err error) *MockJob_Progress_Call {
	_c.Call.Return(getJobProgressResponse, err)
	return _c
}

func (_c *MockJob_Progress_Call) RunAndReturn(run func(ctx context.Context, projectID string, jobUID string) (job.GetJobProgressResponse, error)) *MockJob_Progress_Call {
	_c.Call.Return(run)
	return _c
}

// SearchJobs provides a mock function for the type MockJob
func (_mock *MockJob) SearchJobs(ctx context.Context, projectID string, req job.SearchJobsRequest) (job.ListJobsResponse, error) {
	ret := _mock.Called(ctx, projectID, req)

	if len(ret) == 0 {
		panic("no return value specified for SearchJobs")
	}

	var r0 job.ListJobsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, job.SearchJobsRequest) (job.ListJobsResponse, error)); ok {
		return returnFunc(ctx, projectID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, job.SearchJobsRequest) job.ListJobsResponse); ok {
		r0 = returnFunc(ctx, projectID, req)
	} else {
		r0 = ret.Get(0).(job.ListJobsResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, job.SearchJobsRequest) error); ok {
		r1 = returnFunc(ctx, projectID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockJob_SearchJobs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchJobs'
type MockJob_SearchJobs_Call struct {
	*mock.Call
}

// SearchJobs is a helper method to define mock.On call
//   - ctx context.Context
//   - projectID string
//   - req job.SearchJobsRequest
func (_e *MockJob_Expecter) SearchJobs(ctx interface{}, projectID interface{}, req interface{}) *MockJob_SearchJobs_Call {
	return &MockJob_SearchJobs_Call{Call: _e.mock.On("SearchJobs", ctx, projectID, req)}
}

func (_c *MockJob_SearchJobs_Call) Run(run func(ctx context.Context, projectID string, req job.SearchJobsRequest)) *MockJob_SearchJobs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 job.SearchJobsRequest
		if args[2] != nil {
			arg2 = args[2].(job.SearchJobsRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockJob_SearchJobs_Call) Return(listJobsResponse job.ListJobsResponse, err error) *MockJob_SearchJobs_Call {
	_c.Call.Return(listJobsResponse, err)
	return _c
}

func (_c *MockJob_SearchJobs_Call) RunAndReturn(run func(ctx context.Context, projectID string, req job.SearchJobsRequest) (job.ListJobsResponse, error)) *MockJob_SearchJobs_Call {
	_c.Call.Return(run)
	return _c
}
