// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package glossarymocks

import (
	"context"

	"github.com/Smartling/api-sdk-go/api/glossary"
	"github.com/Smartling/api-sdk-go/helpers/uid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGlossary creates a new instance of MockGlossary. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGlossary(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGlossary {
	mock := &MockGlossary{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGlossary is an autogenerated mock type for the Glossary type
type MockGlossary struct {
	mock.Mock
}

type MockGlossary_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGlossary) EXPECT() *MockGlossary_Expecter {
	return &MockGlossary_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockGlossary
func (_mock *MockGlossary) Create(ctx context.Context, accountUID uid.AccountUID, req glossary.CreateGlossaryRequest) (glossary.CreateGlossaryResponse, error) {
	ret := _mock.Called(ctx, accountUID, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 glossary.CreateGlossaryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uid.AccountUID, glossary.CreateGlossaryRequest) (glossary.CreateGlossaryResponse, error)); ok {
		return returnFunc(ctx, accountUID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uid.AccountUID, glossary.CreateGlossaryRequest) glossary.CreateGlossaryResponse); ok {
		r0 = returnFunc(ctx, accountUID, req)
	} else {
		r0 = ret.Get(0).(glossary.CreateGlossaryResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uid.AccountUID, glossary.CreateGlossaryRequest) error); ok {
		r1 = returnFunc(ctx, accountUID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGlossary_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockGlossary_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - accountUID uid.AccountUID
//   - req glossary.CreateGlossaryRequest
func (_e *MockGlossary_Expecter) Create(ctx interface{}, accountUID interface{}, req interface{}) *MockGlossary_Create_Call {
	return &MockGlossary_Create_Call{Call: _e.mock.On("Create", ctx, accountUID, req)}
}

func (_c *MockGlossary_Create_Call) Run(run func(ctx context.Context, accountUID uid.AccountUID, req glossary.CreateGlossaryRequest)) *MockGlossary_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uid.AccountUID
		if args[1] != nil {
			arg1 = args[1].(uid.AccountUID)
		}
		var arg2 glossary.CreateGlossaryRequest
		if args[2] != nil {
			arg2 = args[2].(glossary.CreateGlossaryRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGlossary_Create_Call) Return(createGlossaryResponse glossary.CreateGlossaryResponse, err error) *MockGlossary_Create_Call {
	_c.Call.Return(createGlossaryResponse, err)
	return _c
}

func (_c *MockGlossary_Create_Call) RunAndReturn(run func(ctx context.Context, accountUID uid.AccountUID, req glossary.CreateGlossaryRequest) (glossary.CreateGlossaryResponse, error)) *MockGlossary_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Export provides a mock function for the type MockGlossary
func (_mock *MockGlossary) Export(ctx context.Context, accountUID uid.AccountUID, glossaryUID string, req glossary.ExportGlossaryRequest) (glossary.ExportGlossaryResponse, error) {
	ret := _mock.Called(ctx, accountUID, glossaryUID, req)

	if len(ret) == 0 {
		panic("no return value specified for Export")
	}

	var r0 glossary.ExportGlossaryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uid.AccountUID, string, glossary.ExportGlossaryRequest) (glossary.ExportGlossaryResponse, error)); ok {
		return returnFunc(ctx, accountUID, glossaryUID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uid.AccountUID, string, glossary.ExportGlossaryRequest) glossary.ExportGlossaryResponse); ok {
		r0 = returnFunc(ctx, accountUID, glossaryUID, req)
	} else {
		r0 = ret.Get(0).(glossary.ExportGlossaryResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uid.AccountUID, string, glossary.ExportGlossaryRequest) error); ok {
		r1 = returnFunc(ctx, accountUID, glossaryUID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGlossary_Export_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Export'
type MockGlossary_Export_Call struct {
	*mock.Call
}

// Export is a helper method to define mock.On call
//   - ctx context.Context
//   - accountUID uid.AccountUID
//   - glossaryUID string
//   - req glossary.ExportGlossaryRequest
func (_e *MockGlossary_Expecter) Export(ctx interface{}, accountUID interface{}, glossaryUID interface{}, req interface{}) *MockGlossary_Export_Call {
	return &MockGlossary_Export_Call{Call: _e.mock.On("Export", ctx, accountUID, glossaryUID, req)}
}

func (_c *MockGlossary_Export_Call) Run(run func(ctx context.Context, accountUID uid.AccountUID, glossaryUID string, req glossary.ExportGlossaryRequest)) *MockGlossary_Export_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uid.AccountUID
		if args[1] != nil {
			arg1 = args[1].(uid.AccountUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 glossary.ExportGlossaryRequest
		if args[3] != nil {
			arg3 = args[3].(glossary.ExportGlossaryRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGlossary_Export_Call) Return(exportGlossaryResponse glossary.ExportGlossaryResponse, err error) *MockGlossary_Export_Call {
	_c.Call.Return(exportGlossaryResponse, err)
	return _c
}

func (_c *MockGlossary_Export_Call) RunAndReturn(run func(ctx context.Context, accountUID uid.AccountUID, glossaryUID string, req glossary.ExportGlossaryRequest) (glossary.ExportGlossaryResponse, error)) *MockGlossary_Export_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockGlossary
func (_mock *MockGlossary) Get(ctx context.Context, accountUID uid.AccountUID, glossaryUID string) (glossary.ReadGlossaryResponse, error) {
	ret := _mock.Called(ctx, accountUID, glossaryUID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 glossary.ReadGlossaryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uid.AccountUID, string) (glossary.ReadGlossaryResponse, error)); ok {
		return returnFunc(ctx, accountUID, glossaryUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uid.AccountUID, string) glossary.ReadGlossaryResponse); ok {
		r0 = returnFunc(ctx, accountUID, glossaryUID)
	} else {
		r0 = ret.Get(0).(glossary.ReadGlossaryResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uid.AccountUID, string) error); ok {
		r1 = returnFunc(ctx, accountUID, glossaryUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGlossary_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockGlossary_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - accountUID uid.AccountUID
//   - glossaryUID string
func (_e *MockGlossary_Expecter) Get(ctx interface{}, accountUID interface{}, glossaryUID interface{}) *MockGlossary_Get_Call {
	return &MockGlossary_Get_Call{Call: _e.mock.On("Get", ctx, accountUID, glossaryUID)}
}

func (_c *MockGlossary_Get_Call) Run(run func(ctx context.Context, accountUID uid.AccountUID, glossaryUID string)) *MockGlossary_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uid.AccountUID
		if args[1] != nil {
			arg1 = args[1].(uid.AccountUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGlossary_Get_Call) Return(readGlossaryResponse glossary.ReadGlossaryResponse, err error) *MockGlossary_Get_Call {
	_c.Call.Return(readGlossaryResponse, err)
	return _c
}

func (_c *MockGlossary_Get_Call) RunAndReturn(run func(ctx context.Context, accountUID uid.AccountUID, glossaryUID string) (glossary.ReadGlossaryResponse, error)) *MockGlossary_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByName provides a mock function for the type MockGlossary
func (_mock *MockGlossary) GetByName(ctx context.Context, accountUID uid.AccountUID, name string) ([]glossary.ReadGlossaryResponse, error) {
	ret := _mock.Called(ctx, accountUID, name)

	if len(ret) == 0 {
		panic("no return value specified for GetByName")
	}

	var r0 []glossary.ReadGlossaryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uid.AccountUID, string) ([]glossary.ReadGlossaryResponse, error)); ok {
		return returnFunc(ctx, accountUID, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uid.AccountUID, string) []glossary.ReadGlossaryResponse); ok {
		r0 = returnFunc(ctx, accountUID, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]glossary.ReadGlossaryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uid.AccountUID, string) error); ok {
		r1 = returnFunc(ctx, accountUID, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGlossary_GetByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByName'
type MockGlossary_GetByName_Call struct {
	*mock.Call
}

// GetByName is a helper method to define mock.On call
//   - ctx context.Context
//   - accountUID uid.AccountUID
//   - name string
func (_e *MockGlossary_Expecter) GetByName(ctx interface{}, accountUID interface{}, name interface{}) *MockGlossary_GetByName_Call {
	return &MockGlossary_GetByName_Call{Call: _e.mock.On("GetByName", ctx, accountUID, name)}
}

func (_c *MockGlossary_GetByName_Call) Run(run func(ctx context.Context, accountUID uid.AccountUID, name string)) *MockGlossary_GetByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uid.AccountUID
		if args[1] != nil {
			arg1 = args[1].(uid.AccountUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockGlossary_GetByName_Call) Return(glossaries []glossary.ReadGlossaryResponse, err error) *MockGlossary_GetByName_Call {
	_c.Call.Return(glossaries, err)
	return _c
}

func (_c *MockGlossary_GetByName_Call) RunAndReturn(run func(ctx context.Context, accountUID uid.AccountUID, name string) ([]glossary.ReadGlossaryResponse, error)) *MockGlossary_GetByName_Call {
	_c.Call.Return(run)
	return _c
}

// Import provides a mock function for the type MockGlossary
func (_mock *MockGlossary) Import(ctx context.Context, accountUID uid.AccountUID, glossaryUID string, req glossary.ImportGlossaryRequest) (glossary.ImportGlossaryResponse, error) {
	ret := _mock.Called(ctx, accountUID, glossaryUID, req)

	if len(ret) == 0 {
		panic("no return value specified for Import")
	}

	var r0 glossary.ImportGlossaryResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uid.AccountUID, string, glossary.ImportGlossaryRequest) (glossary.ImportGlossaryResponse, error)); ok {
		return returnFunc(ctx, accountUID, glossaryUID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uid.AccountUID, string, glossary.ImportGlossaryRequest) glossary.ImportGlossaryResponse); ok {
		r0 = returnFunc(ctx, accountUID, glossaryUID, req)
	} else {
		r0 = ret.Get(0).(glossary.ImportGlossaryResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uid.AccountUID, string, glossary.ImportGlossaryRequest) error); ok {
		r1 = returnFunc(ctx, accountUID, glossaryUID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGlossary_Import_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Import'
type MockGlossary_Import_Call struct {
	*mock.Call
}

// Import is a helper method to define mock.On call
//   - ctx context.Context
//   - accountUID uid.AccountUID
//   - glossaryUID string
//   - req glossary.ImportGlossaryRequest
func (_e *MockGlossary_Expecter) Import(ctx interface{}, accountUID interface{}, glossaryUID interface{}, req interface{}) *MockGlossary_Import_Call {
	return &MockGlossary_Import_Call{Call: _e.mock.On("Import", ctx, accountUID, glossaryUID, req)}
}

func (_c *MockGlossary_Import_Call) Run(run func(ctx context.Context, accountUID uid.AccountUID, glossaryUID string, req glossary.ImportGlossaryRequest)) *MockGlossary_Import_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uid.AccountUID
		if args[1] != nil {
			arg1 = args[1].(uid.AccountUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 glossary.ImportGlossaryRequest
		if args[3] != nil {
			arg3 = args[3].(glossary.ImportGlossaryRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGlossary_Import_Call) Return(importGlossaryResponse glossary.ImportGlossaryResponse, err error) *MockGlossary_Import_Call {
	_c.Call.Return(importGlossaryResponse, err)
	return _c
}

func (_c *MockGlossary_Import_Call) RunAndReturn(run func(ctx context.Context, accountUID uid.AccountUID, glossaryUID string, req glossary.ImportGlossaryRequest) (glossary.ImportGlossaryResponse, error)) *MockGlossary_Import_Call {
	_c.Call.Return(run)
	return _c
}

// ImportConfirm provides a mock function for the type MockGlossary
func (_mock *MockGlossary) ImportConfirm(ctx context.Context, accountUID uid.AccountUID, glossaryUID string, importUID string) (bool, error) {
	ret := _mock.Called(ctx, accountUID, glossaryUID, importUID)

	if len(ret) == 0 {
		panic("no return value specified for ImportConfirm")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uid.AccountUID, string, string) (bool, error)); ok {
		return returnFunc(ctx, accountUID, glossaryUID, importUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uid.AccountUID, string, string) bool); ok {
		r0 = returnFunc(ctx, accountUID, glossaryUID, importUID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uid.AccountUID, string, string) error); ok {
		r1 = returnFunc(ctx, accountUID, glossaryUID, importUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGlossary_ImportConfirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportConfirm'
type MockGlossary_ImportConfirm_Call struct {
	*mock.Call
}

// ImportConfirm is a helper method to define mock.On call
//   - ctx context.Context
//   - accountUID uid.AccountUID
//   - glossaryUID string
//   - importUID string
func (_e *MockGlossary_Expecter) ImportConfirm(ctx interface{}, accountUID interface{}, glossaryUID interface{}, importUID interface{}) *MockGlossary_ImportConfirm_Call {
	return &MockGlossary_ImportConfirm_Call{Call: _e.mock.On("ImportConfirm", ctx, accountUID, glossaryUID, importUID)}
}

func (_c *MockGlossary_ImportConfirm_Call) Run(run func(ctx context.Context, accountUID uid.AccountUID, glossaryUID string, importUID string)) *MockGlossary_ImportConfirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uid.AccountUID
		if args[1] != nil {
			arg1 = args[1].(uid.AccountUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGlossary_ImportConfirm_Call) Return(b bool, err error) *MockGlossary_ImportConfirm_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockGlossary_ImportConfirm_Call) RunAndReturn(run func(ctx context.Context, accountUID uid.AccountUID, glossaryUID string, importUID string) (bool, error)) *MockGlossary_ImportConfirm_Call {
	_c.Call.Return(run)
	return _c
}

// ImportStatus provides a mock function for the type MockGlossary
func (_mock *MockGlossary) ImportStatus(ctx context.Context, accountUID uid.AccountUID, glossaryUID string, importUID string) (glossary.ImportStatusResponse, error) {
	ret := _mock.Called(ctx, accountUID, glossaryUID, importUID)

	if len(ret) == 0 {
		panic("no return value specified for ImportStatus")
	}

	var r0 glossary.ImportStatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uid.AccountUID, string, string) (glossary.ImportStatusResponse, error)); ok {
		return returnFunc(ctx, accountUID, glossaryUID, importUID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uid.AccountUID, string, string) glossary.ImportStatusResponse); ok {
		r0 = returnFunc(ctx, accountUID, glossaryUID, importUID)
	} else {
		r0 = ret.Get(0).(glossary.ImportStatusResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uid.AccountUID, string, string) error); ok {
		r1 = returnFunc(ctx, accountUID, glossaryUID, importUID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockGlossary_ImportStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportStatus'
type MockGlossary_ImportStatus_Call struct {
	*mock.Call
}

// ImportStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - accountUID uid.AccountUID
//   - glossaryUID string
//   - importUID string
func (_e *MockGlossary_Expecter) ImportStatus(ctx interface{}, accountUID interface{}, glossaryUID interface{}, importUID interface{}) *MockGlossary_ImportStatus_Call {
	return &MockGlossary_ImportStatus_Call{Call: _e.mock.On("ImportStatus", ctx, accountUID, glossaryUID, importUID)}
}

func (_c *MockGlossary_ImportStatus_Call) Run(run func(ctx context.Context, accountUID uid.AccountUID, glossaryUID string, importUID string)) *MockGlossary_ImportStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uid.AccountUID
		if args[1] != nil {
			arg1 = args[1].(uid.AccountUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGlossary_ImportStatus_Call) Return(importStatusResponse glossary.ImportStatusResponse, err error) *MockGlossary_ImportStatus_Call {
	_c.Call.Return(importStatusResponse, err)
	return _c
}

func (_c *MockGlossary_ImportStatus_Call) RunAndReturn(run func(ctx context.Context, accountUID uid.AccountUID, glossaryUID string, importUID string) (glossary.ImportStatusResponse, error)) *MockGlossary_ImportStatus_Call {
	_c.Call.Return(run)
	return _c
}
